### ISSUE TITLE
Release training code

### ISSUE THREAD

**Issue by tau-yihouxiang** [ToughStoneX/Self-Supervised-MVS#2]
Excellent contributions! When will you release the training code?

**Comment by ToughStoneX** [comment]
Hi, I am currently clearing up the training code.
Due to the graduation affairs like graduation reply at my school in March and April, the release of the code is delayed.
If you meet up with any problems when implementing the code, you can contact me via e-mail: hongbinxu1013@gmail.com, because sometimes I may not check this github repository in time.
Furthermore, if you require the code urgently, I can send the raw code to your e-mail address, although it is still in a mess.

**Comment by ToughStoneX** [comment]
The code is released. ^_^
